# Generated by Django 6.0.7 on 2026-07-18 20:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('stage_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('demo_link', models.URLField(help_text='Link to SoundCloud, Google Drive, DropBox, etc.')),
                ('social_media', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(help_text='Tell us about yourself and your musical goals')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('showcase_image', models.ImageField(blank=True, null=True, upload_to='studio/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('audio_file', models.FileField(upload_to='tracks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac'])])),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('music_key', models.CharField(blank=True, max_length=20, null=True)),
                ('ai_tags', models.JSONField(blank=True, default=list)),
                ('is_premiere', models.BooleanField(default=False)),
                ('premiere_date', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('listener', 'Listener'), ('artist', 'Artist')], default='listener', max_length=10)),
                ('stage_name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_verified_artist', models.BooleanField(default=False, verbose_name='Verified Label Artist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
